##Problema 01 - TEXTO I
##Representação de Dados

Gerar uma matriz, a partir de um ou de ambos os textos anexo.

Temos que ser capazes de voltar ao texto a partir da matriz. Podemos abrir mão de caracteres especiais e pontuação.

Deve ser entregue a matriz, um texto explicando a estratégia e o código fonte utilizado para gerar a matriz (quando houver).


In [ ]:
import copy
import numpy as np
import requests

In [ ]:
# ler arquivos
base_text_1 = "https://raw.githubusercontent.com/meduardaeneves/meduardaeneves.github.io/master/files/personal_projects_data_pt/data_representation_text_matrix/base_text_matrix_representation.txt"
print(base_text_1)

https://raw.githubusercontent.com/meduardaeneves/meduardaeneves.github.io/master/files/personal_projects_data_pt/data_representation_text_matrix/base_text_matrix_representation.txt


In [ ]:
# Fazer a requisição GET para obter o conteúdo do arquivo
response = requests.get(base_text_1)

In [ ]:
if response.status_code == 200:
    file1 = response.text  # Lê o conteúdo do arquivo como texto
    # print(file1)
else:
    print(f"Erro ao baixar o arquivo: {response.status_code}")

In [ ]:
print(file1)

De motu Circulari Fluidorum.

Hypothesis.
Resistentiam, quæ oritur ex defectu lubricitatis partium Fluidi, cæteris paribus, proportionalem esse velocitati, qua partes Fluidi separantur ab invicem.

Prop. LI. Theor. XXXVIII.
Si Cylindrus solidus infinitè longus in fluido uniformi & infinito circa axem positione datum uniformi cum motu revolvatur, & ab hujus impulsu solo agatur Fluidum in Orbem, perseveret autem fluidi pars unaquæque uniformiter in motu suo; dico quod tempora periodica partium fluidi sunt ut ipsarum distantiæ ab axe cylindri.

Sit AFL cylindrus uniformiter circa axem S in orbem actus, & circulis concentricis BGM, CHN, DIO, EKP, &c. distinguatur fluidum in orbes cylindricos innumeros concentricos solidos ejusdem crassitudinis. Et quoniam homogeneum est Fluidum, impressiones contiguorum orbium in se mutuò factæ, erunt (per Hypothesin) ut eorum translationes ab invicem & superficies contiguæ in quibus impressiones fiunt. Si impressio in Orbem aliquem major est vel minor, ex

##Estratégia Utilizada:



A estratégia utilizada foi transformar o texto em uma matriz (lista de listas), onde a quantidade de linhas e colunhas da matriz vai depender da quantidade de linhas que o texto possui e da quantidade máximas de caracteres encontradas em uma linha:
 - Cada linha do texto será uma linha da matriz
 - A quantidade de colunas será definida pela linha que tem o maior número de caracteres
  - nas linhas que tem menos caracteres, será adicionado o texto "None", quantas vezes seja necessário, até que a quantidade de caracteres nessa linha se iguale à linha que contém o máximo de caracteres

Será atribuído um valor numérico para cada palavra diferente encontrada ao longo do texto, utilizando o set(), levando em consideração o "None" que foi adicionado manualmente.

Por fim, de posse da matriz de conversão e da matriz texto completa, onde cada elemento da matriz é uma única string, será possível fazer a conversão da matriz texto para matriz numérica;
   - Serão feitos loopings para encontrar o elemento numérico da matriz de conversão que seja referente a cada elemento da matriz texto.
   - Assim que o elemento é encontrado, da-se início a construção da matriz numérica através da substituição de Strings para números.
   - Por fim, se obtém a matriz numérica desejada

O processo de conversão da matriz numérica para texto é o inverso do apresentado anteriormente:
  - Será utilizada a matriz de conversão para substituir os números pelas palavras referentes a eles
  - Depois de obter uma matriz texto, onde cada elemento vai ser uma palavra, vai ser feita a junção dos elementos da linha, adicionando o espaço entre os elementos.
  - Como resultado vamos obter a matriz onde cada linha va matriz vai ser uma linha do texto original, concluindo assim a conversão dos números para texto.

##Aplicação do código - conversão texto/número

In [ ]:
# criação da lista de palavras, com todas as palavras existentes e uma lista de texto por linhas

qnt_NONE = 0
listaNova = []
lista_palavras = []

for linha in file1.split("\n"):
  novaPalavra = ""
  listaString = []
  for caractere in linha:
    if caractere != " ":
      if caractere != "\n":
        novaPalavra += caractere
    else:
      if caractere == "\n":
        novaPalavra = caractere
      listaString.append(novaPalavra)
      novaPalavra = ''
  if novaPalavra == None:
    qnt_NONE += 1
  listaString.append(novaPalavra)
  listaNova.append(listaString)
  lista_palavras.extend(listaString)

In [ ]:
#remoção do '' da lista de palavras e criação do set, referente a essa lista
#para obter elementos únicos, em seguida atribuição a um valor para cada
#elemento da lista de palavras e apresentação dela:
print(f'Lista de palavras completas (tamanho: {len(lista_palavras)}):\n{lista_palavras}')
lista_palavras_sem_duplicados = list(set(lista_palavras))

#verificar a existência do None no texto e por fim, adicionando-o à lista
print()
print(f'QNT None: {qnt_NONE}')
print()

print(f'Lista de palavras com elementos únicos (tamanho: {len(lista_palavras_sem_duplicados)}):\n{lista_palavras_sem_duplicados}')
print()
lista_palavras_sem_duplicados.append('None')
print(f'Lista de palavras com elementos únicos + None (tamanho: {len(lista_palavras_sem_duplicados)}):\n{lista_palavras_sem_duplicados}')
print()
#criar lista de números para relacionar com as palavras
lista_numeros = []
for i in range(1,(len(lista_palavras_sem_duplicados)+1)):
  lista_numeros.append(i)
print(f'Lista de números (tamanho: {len(lista_numeros)}):\n{lista_numeros}')

#combinação dos números e palavras
combinacao = list(zip(lista_numeros, lista_palavras_sem_duplicados))
#combinacao_dict = [{'numero': numero, 'palavra': palavra} for numero,palavra in combinacao]
print(f'Lista combinada (comprimento: {len(combinacao)}):\n{combinacao}')


Lista de palavras completas (tamanho: 3303):
['De', 'motu', 'Circulari', 'Fluidorum.\r', '\r', 'Hypothesis.\r', 'Resistentiam,', 'quæ', 'oritur', 'ex', 'defectu', 'lubricitatis', 'partium', 'Fluidi,', 'cæteris', 'paribus,', 'proportionalem', 'esse', 'velocitati,', 'qua', 'partes', 'Fluidi', 'separantur', 'ab', 'invicem.\r', '\r', 'Prop.', 'LI.', 'Theor.', 'XXXVIII.\r', 'Si', 'Cylindrus', 'solidus', 'infinitè', 'longus', 'in', 'fluido', 'uniformi', '&', 'infinito', 'circa', 'axem', 'positione', 'datum', 'uniformi', 'cum', 'motu', 'revolvatur,', '&', 'ab', 'hujus', 'impulsu', 'solo', 'agatur', 'Fluidum', 'in', 'Orbem,', 'perseveret', 'autem', 'fluidi', 'pars', 'unaquæque', 'uniformiter', 'in', 'motu', 'suo;', 'dico', 'quod', 'tempora', 'periodica', 'partium', 'fluidi', 'sunt', 'ut', 'ipsarum', 'distantiæ', 'ab', 'axe', 'cylindri.\r', '\r', 'Sit', 'AFL', 'cylindrus', 'uniformiter', 'circa', 'axem', 'S', 'in', 'orbem', 'actus,', '&', 'circulis', 'concentricis', 'BGM,', 'CHN,', 'DIO,', 'EKP

observação: número 1 indica que não há texto naquela linha, apenas uma linha em branco

In [ ]:
# Apresentação da lista de linhas obtida do texto e adição do None, para
# completá-la e todas terem o mesmo comprimento
print()
print(f'Lista de linhas obtidas do texto (comprimento: {len(listaNova)}):\n{listaNova}')

#verificação da linha com maior comprimento para definir qnt de colunas da matriz:
max_colunas = 0
index_escolhido = 0
for index in range(len(listaNova)):
  lenindex = len(listaNova[index])
  if lenindex > max_colunas:
    max_colunas = lenindex
    index_escolhido = index
print(f'\nNúmero de elementos máximo por linha: {max_colunas}: linha: {(index_escolhido+1)}')

for index in range(len(listaNova)):
  while len(listaNova[index]) < max_colunas:
    listaNova[index].append('None')
  #print(f'linha: {(index+1)}, comprimento: {len(listaNova[index])}')
print(f'\nLista de linhas obtidas do texto com None(comprimento: {len(listaNova)}):\n{listaNova}')
print()

# print('Matriz Palavras')
# for linha in listaNova:
#   print(linha,'\n')


Lista de linhas obtidas do texto (comprimento: 72):
[['De', 'motu', 'Circulari', 'Fluidorum.\r'], ['\r'], ['Hypothesis.\r'], ['Resistentiam,', 'quæ', 'oritur', 'ex', 'defectu', 'lubricitatis', 'partium', 'Fluidi,', 'cæteris', 'paribus,', 'proportionalem', 'esse', 'velocitati,', 'qua', 'partes', 'Fluidi', 'separantur', 'ab', 'invicem.\r'], ['\r'], ['Prop.', 'LI.', 'Theor.', 'XXXVIII.\r'], ['Si', 'Cylindrus', 'solidus', 'infinitè', 'longus', 'in', 'fluido', 'uniformi', '&', 'infinito', 'circa', 'axem', 'positione', 'datum', 'uniformi', 'cum', 'motu', 'revolvatur,', '&', 'ab', 'hujus', 'impulsu', 'solo', 'agatur', 'Fluidum', 'in', 'Orbem,', 'perseveret', 'autem', 'fluidi', 'pars', 'unaquæque', 'uniformiter', 'in', 'motu', 'suo;', 'dico', 'quod', 'tempora', 'periodica', 'partium', 'fluidi', 'sunt', 'ut', 'ipsarum', 'distantiæ', 'ab', 'axe', 'cylindri.\r'], ['\r'], ['Sit', 'AFL', 'cylindrus', 'uniformiter', 'circa', 'axem', 'S', 'in', 'orbem', 'actus,', '&', 'circulis', 'concentricis', 'BG

In [ ]:
for linha in listaNova:
  print(linha)

['De', 'motu', 'Circulari', 'Fluidorum.\r', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'Non

In [ ]:
#relacionando elementos da lista do texto com a lista numérica:
# Criando função de conversão
def conversaoTextoMatriz(palavra):
  num_desejado = 0
  for combinacao_numeros in combinacao:
      if combinacao_numeros[1] == palavra:
        num_desejado = combinacao_numeros[0]
  return num_desejado


In [ ]:
#aplicando função de conversão e substituindo os valores
matriz_numerica = copy.deepcopy(listaNova)
for index_linha in range(len(matriz_numerica)):
    for index_coluna in range(len(matriz_numerica[index_linha])):
      num_elemento = conversaoTextoMatriz(matriz_numerica[index_linha][index_coluna])
      matriz_numerica[index_linha][index_coluna] = num_elemento

In [ ]:
#verificar se as linhas estão com o comprimento correto:
qnt_linhas_compErrado = 0
for linha in matriz_numerica:
  if len(linha) < max_colunas:
    qnt_linhas_compErrado += 1
if qnt_linhas_compErrado == 0:
  print('Todas as linhas da matriz estão com o comprimento ok')
else:
  print(f'{qnt_linhas_compErrado} linhas da matriz com comprimento errado')

print(f'\nMatriz Numérica do texto:')
for linha in matriz_numerica:
    print(linha)


Todas as linhas da matriz estão com o comprimento ok

Matriz Numérica do texto:
[1125, 434, 297, 315, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322, 1322

##MATRIZ NUMÉRICA FINAL:

In [ ]:
#conversão da lista em matriz:
matrizNumericaFinal = np.array(matriz_numerica)
np.set_printoptions(threshold = len(matrizNumericaFinal))
print(matrizNumericaFinal)

[[1125  434  297 ... 1322 1322 1322]
 [1169 1322 1322 ... 1322 1322 1322]
 [ 861 1322 1322 ... 1322 1322 1322]
 ...
 [1040 1322 1322 ... 1322 1322 1322]
 [  25  763  231 ... 1187  541 1171]
 [   1 1322 1322 ... 1322 1322 1322]]


##Aplicação do código - conversão número/texto
A partir daqui será feita a conversão inversa de número para texto

In [ ]:
#criando função de conversão de número para texto
def conversaoMatrizNumListaPalavras(numero):
  palavra_desejada = ''
  for combinacao_numeros in combinacao:
      if combinacao_numeros[0] == numero:
        palavra_desejada = combinacao_numeros[1]
  return palavra_desejada

In [ ]:
#aplicação da função de conversão e substituição dos valores
matriz_texto = copy.deepcopy(matriz_numerica)
for index_linha in range(len(matriz_texto)):
    for index_coluna in range(len(matriz_texto[index_linha])):
      palavra = conversaoMatrizNumListaPalavras(matriz_texto[index_linha][index_coluna])
      matriz_texto[index_linha][index_coluna] = palavra

In [ ]:
#verificar se as linhas estão com o comprimento correto:
qnt_linhas_compErrado = 0
for linha in matriz_texto:
  if len(linha) < max_colunas:
    qnt_linhas_compErrado += 1
if qnt_linhas_compErrado == 0:
  print('Todas as linhas da matriz estão com o comprimento ok')
else:
  print(f'{qnt_linhas_compErrado} linhas da matriz com comprimento errado')

print(f'\nMatriz de texto vinda da numérica:')
for linha in matriz_texto:
    print(linha)

Todas as linhas da matriz estão com o comprimento ok

Matriz de texto vinda da numérica:
['De', 'motu', 'Circulari', 'Fluidorum.\r', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'No

In [ ]:
# criar uma lista de texto, onde cada elemento representa uma linha do texto original
Lista_texto_linha = []

for linha in matriz_texto:
    texto = ''
    for elemento in linha:
      if elemento != 'None':
        texto += elemento + ' '
    texto = texto.strip()

    Lista_texto_linha.append(texto)
print(Lista_texto_linha)

['De motu Circulari Fluidorum.', '', 'Hypothesis.', 'Resistentiam, quæ oritur ex defectu lubricitatis partium Fluidi, cæteris paribus, proportionalem esse velocitati, qua partes Fluidi separantur ab invicem.', '', 'Prop. LI. Theor. XXXVIII.', 'Si Cylindrus solidus infinitè longus in fluido uniformi & infinito circa axem positione datum uniformi cum motu revolvatur, & ab hujus impulsu solo agatur Fluidum in Orbem, perseveret autem fluidi pars unaquæque uniformiter in motu suo; dico quod tempora periodica partium fluidi sunt ut ipsarum distantiæ ab axe cylindri.', '', 'Sit AFL cylindrus uniformiter circa axem S in orbem actus, & circulis concentricis BGM, CHN, DIO, EKP, &c. distinguatur fluidum in orbes cylindricos innumeros concentricos solidos ejusdem crassitudinis. Et quoniam homogeneum est Fluidum, impressiones contiguorum orbium in se mutuò factæ, erunt (per Hypothesin) ut eorum translationes ab invicem & superficies contiguæ in quibus impressiones fiunt. Si impressio in Orbem aliqu

In [ ]:
#apresentação do texto original obtido:
for linha in Lista_texto_linha:
  print(linha)

De motu Circulari Fluidorum.

Hypothesis.
Resistentiam, quæ oritur ex defectu lubricitatis partium Fluidi, cæteris paribus, proportionalem esse velocitati, qua partes Fluidi separantur ab invicem.

Prop. LI. Theor. XXXVIII.
Si Cylindrus solidus infinitè longus in fluido uniformi & infinito circa axem positione datum uniformi cum motu revolvatur, & ab hujus impulsu solo agatur Fluidum in Orbem, perseveret autem fluidi pars unaquæque uniformiter in motu suo; dico quod tempora periodica partium fluidi sunt ut ipsarum distantiæ ab axe cylindri.

Sit AFL cylindrus uniformiter circa axem S in orbem actus, & circulis concentricis BGM, CHN, DIO, EKP, &c. distinguatur fluidum in orbes cylindricos innumeros concentricos solidos ejusdem crassitudinis. Et quoniam homogeneum est Fluidum, impressiones contiguorum orbium in se mutuò factæ, erunt (per Hypothesin) ut eorum translationes ab invicem & superficies contiguæ in quibus impressiones fiunt. Si impressio in Orbem aliquem major est vel minor, ex